/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RoomType = IDL.Variant({
  'publicRoom' : IDL.Null,
  'privateRoom' : IDL.Null,
});
export const ProficiencyLevel = IDL.Record({
  'level' : IDL.Text,
  'language' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'age' : IDL.Opt(IDL.Nat),
  'occupation' : IDL.Text,
  'proficiencyLevels' : IDL.Vec(ProficiencyLevel),
  'interests' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'education' : IDL.Text,
  'likes' : IDL.Text,
  'selfIntroduction' : IDL.Text,
  'gender' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
  'dislikes' : IDL.Text,
  'location' : IDL.Text,
  'favoriteTravelDestinations' : IDL.Text,
  'hobbies' : IDL.Text,
  'primaryLanguage' : IDL.Text,
  'relationshipStatus' : IDL.Text,
});
export const Gift = IDL.Record({
  'id' : IDL.Nat,
  'icon' : ExternalBlob,
  'name' : IDL.Text,
  'price' : IDL.Nat,
});
export const Time = IDL.Int;
export const GiftTransaction = IDL.Record({
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'roomId' : IDL.Nat,
  'giftId' : IDL.Nat,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'createRoom' : IDL.Func([IDL.Text, RoomType], [IDL.Nat], []),
  'createStrangerRoom' : IDL.Func([], [IDL.Nat], []),
  'deleteRoom' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGiftCatalog' : IDL.Func([], [IDL.Vec(Gift)], ['query']),
  'getRoomGiftHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(GiftTransaction)],
      ['query'],
    ),
  'getRoomMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getStrangerRoomMessages' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isBlocked' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinStrangerQueue' : IDL.Func([], [], []),
  'pairWithStranger' : IDL.Func([], [IDL.Nat], []),
  'removeFromStrangerQueue' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendGift' : IDL.Func([IDL.Nat, IDL.Principal, IDL.Nat], [], []),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'sendStrangerRoomMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'translateText' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RoomType = IDL.Variant({
    'publicRoom' : IDL.Null,
    'privateRoom' : IDL.Null,
  });
  const ProficiencyLevel = IDL.Record({
    'level' : IDL.Text,
    'language' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'age' : IDL.Opt(IDL.Nat),
    'occupation' : IDL.Text,
    'proficiencyLevels' : IDL.Vec(ProficiencyLevel),
    'interests' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'education' : IDL.Text,
    'likes' : IDL.Text,
    'selfIntroduction' : IDL.Text,
    'gender' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
    'dislikes' : IDL.Text,
    'location' : IDL.Text,
    'favoriteTravelDestinations' : IDL.Text,
    'hobbies' : IDL.Text,
    'primaryLanguage' : IDL.Text,
    'relationshipStatus' : IDL.Text,
  });
  const Gift = IDL.Record({
    'id' : IDL.Nat,
    'icon' : ExternalBlob,
    'name' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Time = IDL.Int;
  const GiftTransaction = IDL.Record({
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'roomId' : IDL.Nat,
    'giftId' : IDL.Nat,
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'createRoom' : IDL.Func([IDL.Text, RoomType], [IDL.Nat], []),
    'createStrangerRoom' : IDL.Func([], [IDL.Nat], []),
    'deleteRoom' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGiftCatalog' : IDL.Func([], [IDL.Vec(Gift)], ['query']),
    'getRoomGiftHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(GiftTransaction)],
        ['query'],
      ),
    'getRoomMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getStrangerRoomMessages' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isBlocked' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinStrangerQueue' : IDL.Func([], [], []),
    'pairWithStranger' : IDL.Func([], [IDL.Nat], []),
    'removeFromStrangerQueue' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendGift' : IDL.Func([IDL.Nat, IDL.Principal, IDL.Nat], [], []),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'sendStrangerRoomMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'translateText' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };